### ISSUE TITLE
.ifne cannot compare Addresses

### ISSUE THREAD

**Issue by bkrug** [endlos99/xdt99#32] opened 2022-01-13 01:16 UTC
Thank you for creating this extremely useful utility.

My assembly code contains the following code:
```
       .ifne $, >603E
       .error 'Directory of Addresses has moved. '
       .endif
```

When I assemble my code I get the following stack trace:
```
Traceback (most recent call last):
  File "C:\Program Files Uninstalled\xdt99-3.2.0\xas99.py", line 3443, in <module>
    status = main()
  File "C:\Program Files Uninstalled\xdt99-3.2.0\xas99.py", line 3340, in main
    asm.assemble(dirname, basename)
  File "C:\Program Files Uninstalled\xdt99-3.2.0\xas99.py", line 2272, in assemble
    self.symasm.assemble_pass_1(srcname)  # continue even with errors, to display them all
  File "C:\Program Files Uninstalled\xdt99-3.2.0\xas99.py", line 2143, in assemble_pass_1
    keep, add_label, operands, line = self.parser.prep.process(self, label, mnemonic, operands, line)
  File "C:\Program Files Uninstalled\xdt99-3.2.0\xas99.py", line 1460, in process
    fn(self, asm, operands)
  File "C:\Program Files Uninstalled\xdt99-3.2.0\xas99.py", line 1371, in IFNE
    self.parse = Util.cmp(*self.args(ops)) != 0 if self.parse else None
  File "C:\Program Files Uninstalled\xdt99-3.2.0\xas99.py", line 57, in cmp
    return (x > y) - (x < y)
TypeError: '>' not supported between instances of 'Address' and 'int'
```

I am using:

- xdt99 version 3.2.0
- Python version 3.8.5
- Windows 10

Thanks!

**Comment by bkrug** [comment] 2022-01-13 01:18
I'm assembling using this command:
xas99.py 'myfile.asm' -S -R -L 'myfile.lst'

**Comment by endlos99** [comment] 2022-01-14 14:57
Thanks for your report!  At first I couldn't reproduce it, but then I found out that you must be assembling a relocatable program.

You could argue that comparing a relocatable address to something is not particular useful, since the relocatable address ($ in your case) might become something else altogether when the program is loaded into memory.

But I think it is still useful, and made a fix for it.  Unfortunately, I cannot push it right now, since I'm working on the IDE plugins, but you should get it sometime next week.  I'll let you know when I push it.

**Comment by bkrug** [comment] 2022-01-14 19:28
Thanks, I'll look out for it.

And you're right I'm working with relocatable addresses, but am still interested in addresses relative to the beginning of the file. I'll probably change my original condition to:

       .ifne $, >3E

or

       .ifne >6000+$, >603E

**Comment by endlos99** [comment] 2022-02-03 17:22
Your fix has been release with version 3.3.0.  Please check if it works for you now, and reopen this ticket if not.

Regarding your two comparisons, they're equivalent, but I'd prefer the simpler one. :-)

**Closed as completed by endlos99** 2022-02-03 17:22 UTC

**Comment by bkrug** [comment] 2022-02-16 05:28
Thanks for your help! Nevertheless, I downloaded both 3.3.0 and 3.3.1 and still see the issue in both versions. I'll try sharing more of my code with you and maybe it will be easier to reproduce.

But my use case may be very much an edge case, and I managed to create my own hack resolution to your python code in 3.2.0. Judge for yourself if a fix would benefit other programmers, but here's the information in case you are interested.

After assembling the file BANKMUSIC.asm or BANKCOLUMN.asm, I see this message:
```
> *** <1> **** - 
***** Warning: Comparing against relocatable address
```

I have a powershell script for assembling my source files and it contains both of these code blocks. I prefer to assemble most source files independently so that most labels are in local scope.
```
#Assembling files
write-host 'Assembling source code'
ForEach($file in $fileList) {
    $asmFile = $file + '.asm'
    $lstFile = $file + '.lst'
    write-host '    ' $asmFile
    xas99.py $asmFile -S -R -L $lstFile
}
```

But then the powershell script combines the object files into 4 different cartridge banks
```
write-host 'Creating bank 1 of cartridge'
xas99.py -b -a ">6000" -o move-bank1.bin -l `
    BANKMUSIC.obj `
    VAR.obj `
    MUSIC.obj `
    TUNE.obj `
    SIGNAL.obj
```

BANKMUSIC.asm contains the code below. 3 of the 4 banks has a directory stored at identical locations.
```
       DEF  DIREND
*
       REF  PLYINT,PLYMSC                   Ref from MUSIC
       REF  BATSND,ENMSND,SLDSND            Ref from SIGNAL

       COPY 'BANKALL.asm'

*
* Directory of Bank Addresses
*
* Routines
       DATA PLYINT                         Initialize Music variables
       DATA PLYMSC                         Play music and sound effects
* Other addresses
       DATA BATSND,ENMSND,SLDSND
DIREND
```

BANKCOLUMN.asm is the same idea.
```
       REF  SCRINT,VDPSUP,SCRWIN,WRTSCR     Ref from SCRNWRT

       COPY 'BANKALL.asm'

*
* Directory of Bank Addresses
*
* Routines
       DATA SCRINT,VDPSUP,SCRWIN,WRTSCR
```

BANKALL.asm contains:
```
*
* Code that exists at beginning of every bank
*

BANK0  EQU  >6000
BANK1  EQU  >6002
BANK2  EQU  >6004
BANK3  EQU  >6006

********@*****@*********************@**************************
*--------------------------------------------------------------
* Cartridge header
*--------------------------------------------------------------
* Since this header is not absolutely positioned at >6000,
* it is important to include '-a ">6000"' in the xas99.py
* command when linking files into a cartridge.
       BYTE  >AA,1,1,0,0,0
       DATA  PROG
       BYTE  0,0,0,0,0,0,0,0
PROG   DATA  0
       DATA  START
       BYTE  TITLE1-TITLE
TITLE  TEXT  'BEN'
       BYTE  >27
       TEXT  'S GAME'
TITLE1
       EVEN

*
* Switch to a bank and run a routine in it
*
* R0 = selected bank
* R1 = address within Directory of Addresses
*
BANKSW MOV  *R11+,R0
       MOV  *R11+,R1
       DECT R10
       MOV  R11,*R10
* select bank based on value in R0
       SETO *R0
* Let R2 = address recorded in Directory of Addresses
* Branch to that address
       MOV  *R1,R2
       BL   *R2
* select main branch
       SETO @BANK0
* return
       MOV  *R10+,R11
       RT

*
* On startup, The TI is supposedly inconsistent at picking an initial bank.
* Select the correct starting bank here.
*
START  SETO @BANK0
* At the next address,
* bank 0 should have executable code,
* other banks should contain a Directory of Addresses

*
* Directory of Bank Addresses
*
* The Directory of addresses (located here)
* is a series of data entries that contain addresses.
* Each of these addresses points to a routine or structure in the current bank,
* but indirectly referenced by another bank.
* Compare the contents of BANKMUSIC.asm to DIRMUSIC.asm.
* These files contain the same labels, in the same order,
* _but_ with different values.

       .ifne  $, >3A
       .error 'Directory of Bank Addresses has moved. '
       .endif
```

**Comment by bkrug** [comment] 2022-02-16 06:05
Thanks for your help!

I started using 3.3.1, and the comparison with a relocatable address is now a warning instead of throwing an exception. My program assembles correctly.

**Comment by endlos99** [comment] 2022-02-16 17:31
I now have second thoughts about this warning.  I think it should be fine, say,  to compare the program size again an upper limit for relocatable programs.  I'll remove the warning again in the next release.

**Comment by endlos99** [comment] 2022-02-16 17:47
Removed with 3.3.2.
